-- =========================================================
-- Flagship End-to-End Analytics Project
-- File: 04_advanced_analysis.sql
-- Purpose: Perform advanced business analysis
-- Database: flagship_analytics
-- =========================================================


-- =========================================================
-- CUSTOMER RANKING BY REVENUE
-- Purpose:
-- Rank customers based on their total revenue contribution.
-- =========================================================

WITH customer_revenue AS (
    SELECT
        customer_id,
        ROUND(SUM(revenue), 2) AS total_revenue
    FROM orders_clean
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_revenue,
    RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank
FROM customer_revenue
ORDER BY revenue_rank;
-- =========================================================
-- TOP PRODUCT PER CATEGORY
-- Purpose:
-- Identify the highest revenue-generating product
-- within each product category.
-- =========================================================

WITH product_revenue AS (
    SELECT
        p.category,
        p.product_id,
        p.product_name,
        ROUND(SUM(o.revenue), 2) AS total_revenue
    FROM orders_clean o
    JOIN products p
        ON o.product_id = p.product_id
    GROUP BY
        p.category,
        p.product_id,
        p.product_name
),

ranked_products AS (
    SELECT
        category,
        product_id,
        product_name,
        total_revenue,
        RANK() OVER (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS product_rank
    FROM product_revenue
)

SELECT
    category,
    product_id,
    product_name,
    total_revenue
FROM ranked_products
WHERE product_rank = 1
ORDER BY category;
-- =========================================================
-- MONTHLY REVENUE GROWTH
-- Purpose:
-- Compare each month's revenue with the previous month
-- and calculate month-over-month growth percentage.
-- =========================================================

WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC('month', order_date)::date AS order_month,
        SUM(revenue) AS total_revenue
    FROM orders_clean
    GROUP BY DATE_TRUNC('month', order_date)
),

revenue_with_previous AS (
    SELECT
        order_month,
        total_revenue,
        LAG(total_revenue) OVER (
            ORDER BY order_month
        ) AS previous_month_revenue
    FROM monthly_revenue
)

SELECT
    order_month,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND(previous_month_revenue, 2) AS previous_month_revenue,
    ROUND(
        ((total_revenue - previous_month_revenue)
        / NULLIF(previous_month_revenue, 0)) * 100,
        2
    ) AS monthly_growth_pct
FROM revenue_with_previous
ORDER BY order_month;
-- =========================================================
-- RUNNING REVENUE
-- Purpose:
-- Track cumulative revenue over time.
-- =========================================================

WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC('month', order_date)::date AS order_month,
        SUM(revenue) AS total_revenue
    FROM orders_clean
    GROUP BY DATE_TRUNC('month', order_date)
)

SELECT
    order_month,
    ROUND(total_revenue, 2) AS monthly_revenue,
    ROUND(
        SUM(total_revenue) OVER (
            ORDER BY order_month
        ),
        2
    ) AS running_revenue
FROM monthly_revenue
ORDER BY order_month;
-- =========================================================
-- PRODUCT REVENUE CONTRIBUTION
-- Purpose:
-- Measure each product's percentage contribution
-- to total business revenue.
-- =========================================================

WITH product_revenue AS (
    SELECT
        p.product_id,
        p.product_name,
        p.category,
        SUM(o.revenue) AS total_revenue
    FROM orders_clean o
    JOIN products p
        ON o.product_id = p.product_id
    GROUP BY
        p.product_id,
        p.product_name,
        p.category
)

SELECT
    product_id,
    product_name,
    category,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND(
        (total_revenue / SUM(total_revenue) OVER ()) * 100,
        2
    ) AS revenue_contribution_pct
FROM product_revenue
ORDER BY total_revenue DESC;
-- =========================================================
-- REPEAT VS ONE-TIME CUSTOMER REVENUE CONTRIBUTION
-- Purpose:
-- Compare how much revenue is generated by repeat
-- customers versus one-time customers.
-- =========================================================

WITH customer_summary AS (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders,
        SUM(revenue) AS total_revenue
    FROM orders_clean
    GROUP BY customer_id
)

SELECT
    CASE
        WHEN total_orders = 1 THEN 'One-Time Customer'
        ELSE 'Repeat Customer'
    END AS customer_type,
    COUNT(*) AS total_customers,
    ROUND(SUM(total_revenue), 2) AS total_revenue,
    ROUND(
        SUM(total_revenue) / SUM(SUM(total_revenue)) OVER () * 100,
        2
    ) AS revenue_contribution_pct
FROM customer_summary
GROUP BY customer_type
ORDER BY total_revenue DESC;
-- =========================================================
-- CUSTOMER VALUE SEGMENTATION
-- Purpose:
-- Segment customers based on total revenue contribution
-- for easier business targeting.
-- =========================================================

WITH customer_value AS (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders,
        SUM(revenue) AS total_revenue
    FROM orders_clean
    GROUP BY customer_id
),

segmented_customers AS (
    SELECT
        customer_id,
        total_orders,
        total_revenue,
        NTILE(4) OVER (
            ORDER BY total_revenue DESC
        ) AS value_quartile
    FROM customer_value
)

SELECT
    customer_id,
    total_orders,
    ROUND(total_revenue, 2) AS total_revenue,
    CASE
        WHEN value_quartile = 1 THEN 'High Value'
        WHEN value_quartile = 2 THEN 'Medium-High Value'
        WHEN value_quartile = 3 THEN 'Medium-Low Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM segmented_customers
ORDER BY total_revenue DESC;